server:
  port: 8001

spring:
  application:
    name: MEDICALCARE-PROVIDE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://62.234.54.171:3306/medicalcare?zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 20000                                  # 等待连接获取的最大超时时间
  redis:
    host: 62.234.54.171
    port: 6379
  http:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB


mybatis:      # mybatis配置文件所在路径
  type-aliases-package: com.medicalcare.entity    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mapper/**/*.xml


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.medicalcare.entity


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka


filePath: G:\IdenProject\medicalcare\hospital\src\assets\img\


imgPath: QQ图片20190614234045.jpg


